# Flight Data Fusion

In [1]:
import pandas as pd

### Input Files

In [2]:
input_file_aaa = "../data/2011-12-01-dataaa.csv"
input_file_airtravelcenter = "../data/2011-12-01-dataairtravelcenter.csv"
input_file_dfw = "../data/2011-12-01-datadfw.csv"

### Read in the files into one data frame

In [14]:
dfaaa = pd.read_csv(input_file_aaa, delimiter=';', header=0)
dfatc = pd.read_csv(input_file_airtravelcenter, delimiter=';', header=0)
dfdfw = pd.read_csv(input_file_dfw, delimiter=';', header=0)
df = pd.concat([dfaaa, dfatc, dfdfw], ignore_index=True).sort_values(by=['flightno'])
#print(df.dtypes)
df['depsched'] = pd.to_datetime(df['depsched'])
df['depact'] = pd.to_datetime(df['depact'])
df['depgate'] = df['depgate'].astype(str)   
df['arrivalsched'] = pd.to_datetime(df['arrivalsched'])
df['arrivalact'] = pd.to_datetime(df['arrivalact'])
df['arrivalgat'] = df['arrivalgat'].astype(str)
#print(df.dtypes)
df

,website,flightno,depsched,depact,depgate,arrivalsched,arrivalact,arrivalgat
164,aa,AA-10-LAX-JFK,2011-12-01 21:20:00,NaT,47B,2011-12-02 05:30:00,NaT,42
908,airtravelcenter,AA-10-LAX-JFK,NaT,2011-12-01 21:37:00,nan,NaT,2011-12-02 05:15:00,nan
533,airtravelcenter,AA-1007-MIA-PHX,NaT,2011-12-01 17:09:00,nan,NaT,2011-12-01 19:43:00,nan
36,aa,AA-1007-MIA-PHX,2011-12-01 16:55:00,2011-12-01 17:08:00,D5,2011-12-01 20:05:00,2011-12-01 19:55:00,4
402,airtravelcenter,AA-1007-TPA-MIA,NaT,2011-12-01 14:06:00,nan,NaT,2011-12-01 14:51:00,nan
...,...,...,...,...,...,...,...,...
647,airtravelcenter,UA-968-DEN-TUL,NaT,2011-12-01 19:53:00,nan,NaT,2011-12-01 22:03:00,nan
792,airtravelcenter,UA-968-GEG-DEN,NaT,2011-12-01 14:18:00,nan,NaT,2011-12-01 17:17:00,nan
608,airtravelcenter,UA-972-ORD-BRU,NaT,2011-12-01 18:50:00,nan,NaT,2011-12-02 09:01:00,nan
991,airtravelcenter,UA-972-SFO-ORD,NaT,2011-12-01 10:05:00,nan,NaT,2011-12-01 15:29:00,nan
645,airtravelcenter,UA-996-LAX-ORD,NaT,2011-12-01 17:32:00,nan,NaT,2011-12-01 23:04:00,nan

### Remove Duplicates

In [15]:
df_without_duplicates = df.drop_duplicates(["flightno"]).reset_index(drop=True)
df_without_duplicates

,website,flightno,depsched,depact,depgate,arrivalsched,arrivalact,arrivalgat
0,aa,AA-10-LAX-JFK,2011-12-01 21:20:00,NaT,47B,2011-12-02 05:30:00,NaT,42
1,airtravelcenter,AA-1007-MIA-PHX,NaT,2011-12-01 17:09:00,nan,NaT,2011-12-01 19:43:00,nan
2,airtravelcenter,AA-1007-TPA-MIA,NaT,2011-12-01 14:06:00,nan,NaT,2011-12-01 14:51:00,nan
3,aa,AA-1011-MIA-GCM,2011-12-01 19:15:00,2011-12-01 19:29:00,D17,2011-12-01 20:40:00,2011-12-01 20:36:00,nan
4,airtravelcenter,AA-1039-ATL-MIA,NaT,2011-12-01 13:45:00,nan,NaT,2011-12-01 15:09:00,nan
...,...,...,...,...,...,...,...,...
1183,airtravelcenter,UA-968-DEN-TUL,NaT,2011-12-01 19:53:00,nan,NaT,2011-12-01 22:03:00,nan
1184,airtravelcenter,UA-968-GEG-DEN,NaT,2011-12-01 14:18:00,nan,NaT,2011-12-01 17:17:00,nan
1185,airtravelcenter,UA-972-ORD-BRU,NaT,2011-12-01 18:50:00,nan,NaT,2011-12-02 09:01:00,nan
1186,airtravelcenter,UA-972-SFO-ORD,NaT,2011-12-01 10:05:00,nan,NaT,2011-12-01 15:29:00,nan
1187,airtravelcenter,UA-996-LAX-ORD,NaT,2011-12-01 17:32:00,nan,NaT,2011-12-01 23:04:00,nan

### Aggregation of the instances

In [16]:
df_with_agg= df.groupby('flightno').agg({
        'depsched': 'mean',
        'depact': 'mean',
        'depgate': lambda x: x.mode()[0],
        'arrivalsched': 'mean',
        'arrivalact': 'mean',
        'arrivalgat': lambda x: x.mode()[0]
    }).reset_index()    
df_with_agg

,flightno,depsched,depact,depgate,arrivalsched,arrivalact,arrivalgat
0,AA-10-LAX-JFK,2011-12-01 21:20:00,2011-12-01 21:37:00,47B,2011-12-02 05:30:00,2011-12-02 05:15:00,42
1,AA-1007-MIA-PHX,2011-12-01 16:55:00,2011-12-01 17:08:30,D5,2011-12-01 20:05:00,2011-12-01 19:49:00,4
2,AA-1007-TPA-MIA,2011-12-01 13:55:00,2011-12-01 14:06:30,F78,2011-12-01 15:00:00,2011-12-01 14:54:00,D5
3,AA-1011-MIA-GCM,2011-12-01 19:15:00,2011-12-01 19:29:00,D17,2011-12-01 20:40:00,2011-12-01 20:35:00,nan
4,AA-1039-ATL-MIA,2011-12-01 13:25:00,2011-12-01 13:45:30,T11,2011-12-01 15:20:00,2011-12-01 15:11:30,D48
...,...,...,...,...,...,...,...
1183,UA-968-DEN-TUL,NaT,2011-12-01 19:53:00,nan,NaT,2011-12-01 22:03:00,nan
1184,UA-968-GEG-DEN,NaT,2011-12-01 14:18:00,nan,NaT,2011-12-01 17:17:00,nan
1185,UA-972-ORD-BRU,NaT,2011-12-01 18:50:00,nan,NaT,2011-12-02 09:01:00,nan
1186,UA-972-SFO-ORD,NaT,2011-12-01 10:05:00,nan,NaT,2011-12-01 15:29:00,nan
1187,UA-996-LAX-ORD,NaT,2011-12-01 17:32:00,nan,NaT,2011-12-01 23:04:00,nan